spring:
    kafka:
        bootstrap-servers: localhost:9094
        client-id: my-application-test
        listener:
            ack-mode: MANUAL_IMMEDIATE
        producer:
            acks: all

            ## CUSTOM CONFIGURATIONS FOR IDEMPOTENCE (NECESSARY ACKS=ALL)
            enable:
                idempotence: true

            ## CUSTOM CONFIGURATIONS FOR TIMEOUTS
            timeout:
                ms:
                    request: 70000
                    delivery: 100000

        consumer:
            group-id: mygroup-test

            ## WORKS WITH LISTENER.ACK_MODE
            enable-auto-commit: false

            auto:
                offset:
                    reset: earliest

        ## CUSTOM CONFIGURATIONS FOR TOPIC NAME
        topics:
            test: onlytests
